#!/usr/bin/env bash

versions=(
1.1.3
1.1.4
1.1.5
1.2
1.2.1
1.2.2
1.3
1.3.1
1.3.2
1.4
)

for version in "${versions[@]}"; do
    rm -fr streamsupport/src/main/java
    cp -a .zip/streamsupport-${version}-src/src/main/java streamsupport/src/main/java
    git add -A
    git commit -am "$version"
    git tag "$version"
done
